services:
  web:
    build: .
    container_name: inventarios_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/           # hot-reload en dev
    environment:
      - APP_URL=http://localhost:8080/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: inventarios_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: inventarios
      MYSQL_USER: usuario
      MYSQL_PASSWORD: userpw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/sistema.sql:/docker-entrypoint-initdb.d/1-schema.sql  # ← tu dump

volumes:
  db_data:
